
import calendar
import os
from datetime import datetime

from fpdf import FPDF

NAVY = (20, 33, 61)
AMBER = (252, 163, 17)
SLATE = (73, 84, 100)
LIGHT_GREY = (237, 238, 240)


class PlaceTrackPDF(FPDF):
    """Shared page chrome (header/footer) for every PlaceTrack PDF."""

    doc_title = "PlaceTrack"

    def header(self):
        self.set_fill_color(*NAVY)
        self.rect(0, 0, self.w, 22, style="F")
        self.set_xy(10, 6)
        self.set_font("Helvetica", "B", 16)
        self.set_text_color(255, 255, 255)
        self.cell(0, 10, "PlaceTrack", ln=0)
        self.set_font("Helvetica", "", 10)
        self.set_xy(-70, 8)
        self.cell(60, 10, self.doc_title, align="R")
        self.set_y(26)
        self.set_text_color(0, 0, 0)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(*SLATE)
        self.cell(0, 10, f"Generated by PlaceTrack | Page {self.page_no()}", align="C")


def _section_title(pdf: PlaceTrackPDF, text: str):
    pdf.ln(4)
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(*NAVY)
    pdf.cell(0, 8, text, ln=1)
    pdf.set_draw_color(*AMBER)
    pdf.set_line_width(0.8)
    y = pdf.get_y()
    pdf.line(10, y, 60, y)
    pdf.ln(4)
    pdf.set_text_color(0, 0, 0)


def _stat_row(pdf: PlaceTrackPDF, label: str, value):
    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(*SLATE)
    pdf.cell(90, 8, label)
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(*NAVY)
    pdf.cell(0, 8, str(value), ln=1)


def generate_monthly_report_pdf(report_data: dict, output_path: str) -> str:
    """report_data keys: month, year, drives_conducted, students_applied,
    students_selected, top_drives (list of dicts), branch_breakdown (dict)."""
    month_name = calendar.month_name[report_data["month"]]
    pdf = PlaceTrackPDF()
    pdf.doc_title = "Monthly Placement Activity Report"
    pdf.add_page()

    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(*NAVY)
    pdf.cell(0, 12, f"{month_name} {report_data['year']} - Activity Report", ln=1)
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(*SLATE)
    pdf.cell(0, 6, f"Generated on {datetime.utcnow().strftime('%d %b %Y, %H:%M UTC')}", ln=1)

    _section_title(pdf, "Summary")
    _stat_row(pdf, "Placement drives conducted", report_data.get("drives_conducted", 0))
    _stat_row(pdf, "Students who applied", report_data.get("students_applied", 0))
    _stat_row(pdf, "Students selected", report_data.get("students_selected", 0))
    conv = report_data.get("students_applied") or 0
    conv_rate = (
        f"{(report_data.get('students_selected', 0) / conv * 100):.1f}%" if conv else "N/A"
    )
    _stat_row(pdf, "Selection conversion rate", conv_rate)

    top_drives = report_data.get("top_drives") or []
    if top_drives:
        _section_title(pdf, "Drives Closed / Reviewed This Month")
        pdf.set_fill_color(*LIGHT_GREY)
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(70, 8, "Company", border=0, fill=True)
        pdf.cell(60, 8, "Role", border=0, fill=True)
        pdf.cell(30, 8, "Applicants", border=0, fill=True)
        pdf.cell(30, 8, "Selected", border=0, fill=True, ln=1)
        pdf.set_font("Helvetica", "", 10)
        for row in top_drives:
            pdf.cell(70, 8, str(row.get("company_name", ""))[:32])
            pdf.cell(60, 8, str(row.get("job_title", ""))[:28])
            pdf.cell(30, 8, str(row.get("applicant_count", 0)))
            pdf.cell(30, 8, str(row.get("selected_count", 0)), ln=1)

    branch_breakdown = report_data.get("branch_breakdown") or {}
    if branch_breakdown:
        _section_title(pdf, "Selections by Branch")
        pdf.set_font("Helvetica", "", 10)
        for branch, count in branch_breakdown.items():
            pdf.cell(0, 7, f"- {branch}: {count}", ln=1)

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    pdf.output(output_path)
    return output_path


def generate_offer_letter_pdf(data: dict, output_path: str) -> str:
    """data keys: student_name, roll_number, branch, company_name, job_title,
    package_lpa, drive_date, hr_contact_name."""
    pdf = PlaceTrackPDF()
    pdf.doc_title = "Offer Letter (Dummy / Demo)"
    pdf.add_page()
    pdf.ln(10)

    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 8, datetime.utcnow().strftime("Date: %d %B %Y"), ln=1)
    pdf.ln(4)

    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(*NAVY)
    pdf.cell(0, 8, f"Dear {data.get('student_name', 'Candidate')},", ln=1)
    pdf.ln(2)

    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(0, 0, 0)
    body = (
        f"Congratulations! On behalf of {data.get('company_name', 'the company')}, "
        f"we are pleased to offer you the position of \"{data.get('job_title', '')}\" "
        f"through the campus placement drive conducted on "
        f"{data.get('drive_date', 'the scheduled date')}. This letter is a demo "
        f"artifact generated by PlaceTrack for academic project evaluation "
        f"purposes and does not constitute a real employment contract."
    )
    pdf.multi_cell(0, 7, body)
    pdf.ln(4)

    _section_title(pdf, "Offer Details")
    _stat_row(pdf, "Candidate", data.get("student_name", ""))
    _stat_row(pdf, "Roll Number", data.get("roll_number", ""))
    _stat_row(pdf, "Branch", data.get("branch", ""))
    _stat_row(pdf, "Role", data.get("job_title", ""))
    _stat_row(pdf, "Annual Package", f"{data.get('package_lpa', 'N/A')} LPA")
    _stat_row(pdf, "Reporting Company", data.get("company_name", ""))

    pdf.ln(10)
    pdf.set_font("Helvetica", "", 11)
    pdf.multi_cell(0, 7, "We look forward to welcoming you to the team.\n\nBest regards,")
    pdf.ln(4)
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 7, data.get("hr_contact_name", "HR Team"), ln=1)
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(*SLATE)
    pdf.cell(0, 7, data.get("company_name", ""), ln=1)

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    pdf.output(output_path)
    return output_path
